"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Zone = exports.EnumRecordType = exports.DNSRecords = exports.Cloudflare = void 0;
const Cloudflare_1 = require("./handler/Cloudflare");
exports.Cloudflare = Cloudflare_1.default;
const DNSRecords_1 = require("./handler/DNSRecords");
exports.DNSRecords = DNSRecords_1.default;
const EnumRecordType_1 = require("./entities/cloudflare/EnumRecordType");
Object.defineProperty(exports, "EnumRecordType", { enumerable: true, get: function () { return EnumRecordType_1.EnumRecordType; } });
const Zone_1 = require("./handler/Zone");
exports.Zone = Zone_1.default;
